#!/bin/sh
# Inicializa schemas y usuarios MySQL por servicio (privilegios mínimos por schema).
# Se ejecuta una sola vez al crear el volumen (docker-entrypoint-initdb.d).
set -e

mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS product_db;
CREATE DATABASE IF NOT EXISTS cart_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS payment_db;

CREATE USER IF NOT EXISTS 'auth_user'@'%' IDENTIFIED BY '$AUTH_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'user_user'@'%' IDENTIFIED BY '$USER_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'product_user'@'%' IDENTIFIED BY '$PRODUCT_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'cart_user'@'%' IDENTIFIED BY '$CART_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'order_user'@'%' IDENTIFIED BY '$ORDER_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'inventory_user'@'%' IDENTIFIED BY '$INVENTORY_DB_PASSWORD';
CREATE USER IF NOT EXISTS 'payment_user'@'%' IDENTIFIED BY '$PAYMENT_DB_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON auth_db.* TO 'auth_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON user_db.* TO 'user_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON product_db.* TO 'product_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON cart_db.* TO 'cart_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON order_db.* TO 'order_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON inventory_db.* TO 'inventory_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON payment_db.* TO 'payment_user'@'%';

FLUSH PRIVILEGES;
EOSQL
